// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-gin v0.0.1
// 	protoc        	  v3.21.11
// source: hello.proto

package internal

import (
	"errors"
	"net/http"
	"github.com/allen-shaw/vodka/demo/internal/api/internal"
	"github.com/gin-gonic/gin"
	api "github.com/allen-shaw/vodka/demo/internal/model/apiinternal"
)

type HelloService struct {
	server hello.HelloService
}

func NewHelloService() *HelloService {
	return &HelloService{server: hello.NewHelloService}
}

func (s *HelloService) Error(c *gin.Context, code int, msg string) {
	c.AbortWithError(code, errors.New(msg))
}

func (s *HelloService) ErrorWithResp(c *gin.Context, code int, resp any) {
	c.AbortWithStatusJSON(code, resp)
}

func (s *HelloService) Success(c *gin.Context, resp any) {
	c.JSON(http.StatusOK, resp)
}

func (s *HelloService) Hello(c *gin.Context) {
	var req api.HelloReq

	err := c.ShouldBindQuery(&req)
	if err != nil {
		s.Error(c, http.StatusBadRequest, "invalid request")
		return
	}

	resp, err := s.server.Hello(c, &req)
	if err != nil {
		s.ErrorWithResp(c, http.StatusInternalServerError, resp)
	}

	s.Success(c, resp)
}
