// Code generated by vodka DO NOT EDIT.
// versions:
// 	vodka       v0.0.1
// 	protoc      v3.21.11
// source: hello.proto

package internal

import (
	"github.com/gin-gonic/gin"
)

func RegisterHelloService(router gin.IRouter, s *HelloService) {
	router.Get("/hello", s.Hello)
}
