// Code generated by vodka DO NOT EDIT.
// versions:
// 	vodka       v0.0.1
// 	protoc      v3.21.11
// source: hello.proto

package internal

import (
	"github.com/gin-gonic/gin"
)

type HTTPServer struct {
	e *gin.Engine
}

func NewHttpServer() *HTTPServer {
	s := new(HTTPServer)
	e := gin.Default()
	s.e = e
	s.register()
	return s
}

func (s *HTTPServer) Run(addr string) error {
	return s.e.Run(addr)
}

func (s *HTTPServer) register() {
	RegisterHelloService(s.e, NewHelloService())
}
